name: Bug Report
description: Create a report to help us reproduce and fix bugs
title: "[Bug Report] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        在仓库中提交bug反馈，请填写下面信息。
        Please fill out the form to submit bug report.

  - type: input
    id: title
    attributes:
      label: Add a title
      description: Briefly summarize the bug
      placeholder: e.g. Search function crash when input special characters
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: What happened?｜发生了什么？
      placeholder: Leave a comment
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: List the steps to reproduce this issue｜复现该问题的操作步骤
      placeholder: Leave a comment
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?｜你期望的正常效果是什么？
      placeholder: Leave a comment
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?｜实际发生的现象
      placeholder: Leave a comment

  - type: dropdown
    id: platform
    attributes:
      label: Platform
      description: Which platform did you encounter this bug｜遇到bug的平台
      options:
        - None 无
        - Web网页端
        - macOS客户端
        - Windows客户端
        - Linux客户端
        - Mobile移动端
    validations:
      required: true

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Screenshots, logs or other related information｜截图、日志或其他相关信息
      placeholder: Leave a comment
